# Generated by Django 5.2.14 on 2026-05-21 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_user_id', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('legacy_name', models.CharField(blank=True, max_length=255)),
                ('raw_user', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RawUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(blank=True, max_length=128)),
                ('max_timestamp', models.DateTimeField(blank=True, null=True)),
                ('max_chat_id', models.CharField(blank=True, max_length=128)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16)),
                ('error_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_chat_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('chat', 'Chat'), ('channel', 'Channel'), ('unknown', 'Unknown')], default='user', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='new', max_length=16)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='support.maxcontact')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=16)),
                ('sender_kind', models.CharField(choices=[('max_user', 'MAX user'), ('manager', 'Manager'), ('system', 'System')], max_length=16)),
                ('max_sender_user_id', models.CharField(blank=True, max_length=128)),
                ('max_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('external_event_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('text_format', models.CharField(choices=[('plain', 'Plain'), ('html', 'HTML'), ('markdown', 'Markdown'), ('unknown', 'Unknown')], default='plain', max_length=16)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('mixed', 'Mixed'), ('service', 'Service'), ('unsupported', 'Unsupported')], default='text', max_length=16)),
                ('raw_message', models.JSONField(blank=True, default=dict)),
                ('send_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_applicable', max_length=24)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=128)),
                ('last_error_text', models.TextField(blank=True)),
                ('provider_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='support.maxcontact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='support.message')),
                ('raw_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='support.rawupdate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ManagerActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='support.conversation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_action_logs', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='support.message')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='support.message'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=16)),
                ('sender_kind', models.CharField(choices=[('max_user', 'MAX user'), ('manager', 'Manager'), ('system', 'System')], max_length=16)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('inline_keyboard', 'Inline keyboard'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('original_file_name', models.CharField(blank=True, max_length=512)),
                ('stored_file', models.FileField(blank=True, upload_to='support_attachments/%Y/%m/%d/')),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('max_payload', models.JSONField(blank=True, default=dict)),
                ('raw_attachment', models.JSONField(blank=True, default=dict)),
                ('upload_status', models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('uploaded', 'Uploaded'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_needed', max_length=24)),
                ('max_upload_token', models.CharField(blank=True, max_length=512)),
                ('max_upload_url', models.URLField(blank=True)),
                ('last_error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='support.maxcontact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.conversation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_attachments', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.message')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('retry_scheduled', 'Retry scheduled')], default='started', max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='support.message')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'unique_together': {('message', 'attempt_no')},
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_message_at'], name='support_con_status_c83d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_to', 'status', 'last_message_at'], name='support_con_assigne_8ed0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact', 'status'], name='support_con_contact_c2d259_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['max_chat_id'], name='support_con_max_cha_9d6265_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='support_mes_message_54bd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['conversation', 'created_at'], name='support_mes_convers_6fe8df_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['upload_status', 'created_at'], name='support_mes_upload__22da9e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='support_mes_convers_c0031e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'provider_created_at', 'id'], name='support_mes_convers_5d76b5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction', 'send_status', 'id'], name='support_mes_directi_40c136_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['manager', 'created_at'], name='support_mes_manager_954b37_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['contact', 'created_at'], name='support_mes_contact_9d06f4_idx'),
        ),
    ]
