# Generated by Django 5.2.14 on 2026-05-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at', '-updated_at', 'id'], 'verbose_name': 'чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='deliveryattempt',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'попытка доставки', 'verbose_name_plural': 'Попытки доставки'},
        ),
        migrations.AlterModelOptions(
            name='manageractionlog',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'лог действия менеджера', 'verbose_name_plural': 'Логи действий менеджеров'},
        ),
        migrations.AlterModelOptions(
            name='maxcontact',
            options={'ordering': ['-last_seen_at', 'id'], 'verbose_name': 'пользователь MAX', 'verbose_name_plural': 'Пользователи MAX'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ['id'], 'verbose_name': 'вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='rawupdate',
            options={'ordering': ['-received_at', 'id'], 'verbose_name': 'сырое событие MAX', 'verbose_name_plural': 'Сырые события MAX'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('chat', 'Чат'), ('channel', 'Канал'), ('unknown', 'Неизвестно')], default='user', max_length=16),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('open', 'Открыт'), ('pending', 'Ожидает'), ('closed', 'Закрыт')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Начата'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('retry_scheduled', 'Повтор запланирован')], default='started', max_length=32),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('mixed', 'Текст и файл'), ('service', 'Сервисное'), ('unsupported', 'Не поддерживается')], default='text', max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_status',
            field=models.CharField(choices=[('not_applicable', 'Не применяется'), ('queued', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='not_applicable', max_length=24),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_kind',
            field=models.CharField(choices=[('max_user', 'Пользователь MAX'), ('manager', 'Менеджер'), ('system', 'Система')], max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_format',
            field=models.CharField(choices=[('plain', 'Обычный текст'), ('html', 'HTML'), ('markdown', 'Markdown'), ('unknown', 'Неизвестно')], default='plain', max_length=16),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('file', 'Файл'), ('inline_keyboard', 'Кнопки'), ('unknown', 'Неизвестно')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=16),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='sender_kind',
            field=models.CharField(choices=[('max_user', 'Пользователь MAX'), ('manager', 'Менеджер'), ('system', 'Система')], max_length=16),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='upload_status',
            field=models.CharField(choices=[('not_needed', 'Не требуется'), ('pending', 'Ожидает'), ('uploaded', 'Загружено'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='not_needed', max_length=24),
        ),
        migrations.AlterField(
            model_name='rawupdate',
            name='status',
            field=models.CharField(choices=[('received', 'Получено'), ('processed', 'Обработано'), ('ignored', 'Проигнорировано'), ('failed', 'Ошибка')], default='received', max_length=16),
        ),
    ]
